### ISSUE TITLE
Rename file

### ISSUE THREAD

**Issue by tosti007** [CFenner/MMM-LocalTransport#16]
The magic mirror framework assumes that the module's main file and folder have the same name as the module, as described [here](https://github.com/MichMich/MagicMirror/tree/develop/modules#files). For this module this is not the case and people have to rename the folder into `localtransport` manualy. Please solve it as not everyone knows this.

**Comment by GHLasse** [comment]
@tosti007: haven't installed any modules from scratch in some time, but don't you create the module folder and then pull the git repository from there? i.e. don't you have to create the folder with name localtransport anyway? 

In localtransport.js it reads `Module.register('localtransport', {` so the file and the module do have the same name. If you think the installation process can be simplified or explained better, please explain how/ submit a pull request. :-)

**Comment by CFenner** [comment]
So the module is now renamed to the standard schema 'MMM-<module-name>'. Does this help?
