### ISSUE TITLE
this.data in localtransport.js conflicts with this.data-object from the module instance properties

### ISSUE THREAD

**Issue by POIMann** [CFenner/MMM-LocalTransport#5]
In 
https://forum.magicmirror.builders/topic/152/face-recognition-with-inferred-light/49
we found that the use of **this.data** in _localtransport.js_ conflicts with **this.data-object** from the module instance properties.

I patched it by replacing “**this.data;**” with “**this.response;**” in all its occurrences in _localtransport.js_.

**Comment by CFenner** [comment]
Can you send a pull request with that?

**Comment by CFenner** [comment]
solved with #15
